### ISSUE TITLE
`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`

### ISSUE THREAD

**Issue by misha-antonenko** [rust-lang/rust-playground#1025]
```
Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```
is what trying to build a piece of code reports on https://play.rust-lang.org/?version=nightly&mode=release&edition=2021

I cannot share the playground (if this is specific to that at all), because the 'share' section keeps loading indefinitely

Reproduces on the trivial code:
```
fn main() {
    let x = 1;
    println!("{}", x);
}
```

Might have something to do with #666

**Comment by dcabanis** [comment]
I am getting the same error on Windows and Linux. With Chrome and Edge.
With firefox I am getting:

JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by shepmaster** [comment]
Issues from this morning are from #1028. Earlier is some other manifestation of #831 or #955

**Comment by rmccampbell** [comment]
I saw the same error today (though it was fixed shortly), maybe there needs to be some validation in whatever XHR request is returning this HTML which is presumably an error page?

**Comment by Powerlax** [comment]
I saw the same error today with relatively trivial code. Please fix!

**Comment by Huyyyyyyyy** [comment]
i got same error today
