### ISSUE TITLE
Rust Playground Server has issues

### ISSUE THREAD

**Issue by ukaeufe** [rust-lang/rust-playground#1028]
Hello Rust Playground does not work due to server issues.
See for example the response when loading the playground first time:

<img width="938" alt="image" src="https://github.com/rust-lang/rust-playground/assets/8048884/2f89dc6c-496a-4ab0-b06b-b95a09962615">

Please check .

Thx

Uwe

**Comment by ukaeufe** [comment]
seems to work again (-:

**Comment by shepmaster** [comment]
`play.rust-lang.org` is a CloudFront proxy to a backend server. The backend server's SSL certificate expired (to be determined why the automatic renewal didn't work) and CloudFront wasn't able to connect.
