### ISSUE TITLE
Assembly output syntax does not match Rust inline assembly syntax

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-playground#1046]
Rust inline assembly expects to be written like this:
```
    crate::arch::asm!(
        "movntps [{mem_addr}], {a}",
        mem_addr = in(reg) mem_addr,
        a = in(xmm_reg) a,
    );
```
However, when dumping the output assembly on the playground, it looks like this:
```
	movntps	%xmm0, (%rdi)
```
Operand order is swapped, and it's using `(%name)` instead of `[name]`. I guess one is AT&T syntax and one is Intel syntax.

Would be good if playground could be consistent with Rust's own inline asm syntax. :)

**Comment by RalfJung** [comment]
Turns out this is a rustc issue: https://github.com/rust-lang/rust/issues/121592

**Comment by PatchMixolydic** [comment]
By default, the playground outputs AT&T syntax, but you can switch to Intel syntax in the config menu:
![Specifically, under the "assembly" subheading](https://github.com/rust-lang/rust-playground/assets/8634700/868ea81f-e1b8-40ce-bfa0-b0b0ab9c8f3c)

... which yields the expected output:
```
	movntps	xmmword ptr [rax], xmm0
```

**Comment by RalfJung** [comment]
Oh fancy, it must have been years since I last checked the config menu. :) Thanks!

**Comment by shepmaster** [comment]
> it must have been years since I last checked the config menu

About 6.5 years... 40d88e560d8384e2db3b94ab279241319870c340
