### ISSUE TITLE
Add the feature "serde" to the crate `either`

### ISSUE THREAD

**Issue by masklinn** [rust-lang/rust-playground#1051]
The playground is nice to demo various things including serde. `either` has serde support, but both the basic externally tagged support and the opt-in untagged support are gated behind a "serde" feature: https://github.com/rayon-rs/either/blob/main/Cargo.toml#L21 so that can't be used on the playground without "vendoring" the crate (at which point having it seems a shame)

**Comment by shepmaster** [comment]
You'll need to ask the either maintainers to [enable that in their Cargo.toml](https://github.com/rust-lang/rust-playground/issues/192#issuecomment-388589736).
