### ISSUE TITLE
Automatically set dark theme

### ISSUE THREAD

**Issue by Flying-Toast** [rust-lang/rust-playground#544]
Using the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media query, it is possible to detect if the user is using a system-wide dark theme, and the Rust Playground should set the editor to a dark theme accordingly.

It would also be nice to have a dark theme that affects the whole site instead of just the ace editor, because the webpage background contrasts badly with the dark editor theme.

**Comment by shepmaster** [comment]
I have a [WIP branch](https://github.com/integer32llc/rust-playground/tree/css-modules-3) converting to CSS modules. As part of that, I plan on adding a dark mode for the whole site, and had indeed planned on using `prefers-color-scheme` when the site is first loaded to automatically select the darker theme.

**Comment by joshtriplett** [comment]
Would this also convert to a dark theme for the compiler/output window, along the lines of the `terminal` color scheme?

Thank you!

**Comment by shepmaster** [comment]
> Would this also convert to a dark theme for the compiler/output window

It's not yet implemented, so it might vary, but that was my intent, yes. That being said, the upgrade path needs to be considered. For those that have already selected an editor theme, should we ignore that when they first load the site with dark theme support? It could be jarring either way...

**Comment by joshtriplett** [comment]
I think it would suffice to 1) switch from the current default theme to the `terminal` theme if the browser is asking for a dark theme, and 2) put a small note somewhere mentioning new dark theme support, for the benefit of folks who have explicitly changed their theme at some point.

**Comment by shepmaster** [comment]
> put a small note somewhere mentioning new dark theme support

yep, there's already support for notes like that (such as when editions were released or pointing people to the Rust survey) and it can even have links to quickly toggle the two suggested themes for comparison.

**Comment by vanillajonathan** [comment]
@shepmaster How is the progress going?

**Comment by shepmaster** [comment]
> How is the progress going

All current progress has been reported in this issue. How would you like to help?

**Comment by vanillajonathan** [comment]
@shepmaster Well your WIP branch doesn't seem to exist anymore, the Rust Playground does not seem to use the prefers-color-scheme CSS media query and your last comment was over a year ago, so I was wondering if maybe there had been some progress since then.

I think @joshtriplett have some good ideas.

**Comment by shepmaster** [comment]
Yes, the ideas are fine. How do you propose to help make the ideas actual?

> your WIP branch doesn't seem to exist

Yes, the playground uses CSS modules now.

**Comment by vanillajonathan** [comment]
Add this to the CSS:

```css
@media (prefers-color-scheme: dark) {
  body { 
    background: #202124; 
  }
}
```

Add this to the JavaScript:
```javascript
const userPrefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

if (userPrefersDark) {
  editor.setTheme("ace/theme/merbivore_soft")
}
```

**Comment by tgross35** [comment]
Hey @shepmaster, would you mind sharing what you had in mind / what the process is?

I'm trying to wrap my head around what this change would look like, this is what I think would be needed:

- Add a dark version of `index.module.css` and `Output.module.css`
- Update `index.tsx` and `Output.tsx` to use the correct css file as needed
- Add an option under the config > UI menu with "dark" "light" and "automatic" options, default to light
- (later, after proveout) default to automatic
