### ISSUE TITLE
"Show Wasm" seems to be broken

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rust-playground#586]
Trying to use "Show Wasm" function on any Rust code seems to produce the following error:

> Unable to locate file for WebAssembly output

**Comment by CYBAI** [comment]
Just tried to reproduce this issue but it seems it's somehow fixed 👀?
I used a simple `main` function with printing hello world and the wasm can be shown properly.

![image](https://user-images.githubusercontent.com/6782666/111803914-e0de1700-8912-11eb-9ab7-4abe83dca3cd.png)

**Comment by RReverser** [comment]
`fn main()` doesn't make sense in raw Wasm (it only works for executables, so at least WASI). Regular `wasm32-unknown-unknown` is meant for libraries, and if you try exporting a function like:

```rust
pub fn foo() {
    
}
```

then the issue still reproduces.

**Comment by CYBAI** [comment]
> `fn main()` doesn't make sense in raw Wasm (it only works for executables, so you need at least WASI)

ah, I see; didn't realize that!

Thank you! I can reproduce it now.

**Comment by Garcia101** [comment]
> Just tried to reproduce this issue but maybe it's somehow fixed eyes? I used a simple `main` function with printing hello world and the wasm can be shown properly.
> 
> ![image](https://user-images.githubusercontent.com/6782666/111803914-e0de1700-8912-11eb-9ab7-4abe83dca3cd.png)

Note that other functions seem to not appear in the output.

E.g.
```rust
pub fn f(x: f32) -> f64 {
 f64::from(x).powi(2)
}
```
I can't find `f` in the assembly, myself.

I haven't reviewed the repository source, but from a light skim of the output generated, it almost seems to be targeting emscripten for output codegen?

Anyways, I came by because I've noticed this for a long time, and was hoping that it could be fixed; is the cause of the issue known yet? Might some extra resources be allocated towards the feature?

**Comment by RalfJung** [comment]
This feature still seems to be [broken](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=da2c2fec26a7c5f885443ce3b687e1bf) -- no wasm output for library crates.

**Comment by RalfJung** [comment]
With a file like this
```rust
#[repr(C)]
pub struct Buffer {
    data: *mut u8,
    len: usize,
    capacity: usize,
    reserve: extern "C" fn(Buffer, usize) -> Buffer,
    drop: extern "C" fn(Buffer),
}

#[no_mangle]
pub extern "C" fn test_grepme(_b: Buffer) {}
```
I *do* get proper wasm output locally: when I run
```
rustc wasm.rs --crate-type cdylib --target wasm32-unknown-unknown && wasm2wat wasm.wasm
```
it shows
```
(module
  (type (;0;) (func (param i32 i32 i32 i32 i32)))
  (func $test_grepme (type 0) (param i32 i32 i32 i32 i32)
    (local i32 i32 i32)
    global.get $__stack_pointer
    local.set 5
    i32.const 32
    local.set 6
    local.get 5
    local.get 6
    i32.sub
    local.set 7
    local.get 7
    local.get 0
    i32.store offset=12
    local.get 7
    local.get 1
    i32.store offset=16
    local.get 7
    local.get 2
    i32.store offset=20
    local.get 7
    local.get 3
    i32.store offset=24
    local.get 7
    local.get 4
    i32.store offset=28
    return)
  (table (;0;) 1 1 funcref)
  (memory (;0;) 16)
  (global $__stack_pointer (mut i32) (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048576))
  (global (;2;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "test_grepme" (func $test_grepme))
  (export "__data_end" (global 1))
  (export "__heap_base" (global 2)))
```
And yet playground shows nothing. So it's not just a problem of functions missing from the wasm file, it's a problem of playground somehow not finding the output that was produced.

**Comment by RReverser** [comment]
With that in mind, one workaround I found since is that you can explicitly specify

```rs
#![crate_type = "cdylib"]

#[no_mangle]
pub fn foo() {}
```

and then output will show up as it will be compiled into a single Wasm file that playground expects. Inconvenient, but at least it works.

**Comment by RalfJung** [comment]
Ah, so the issue is likely that playground uses `--crate-type lib` when it should be using `--crate-type cdylib`.

**Comment by RReverser** [comment]
Probably. Back when I submitted issue I didn't know it works at least sometimes (like when you have `main`), but now given the symptoms this seems like a reasonable conclusion.

**Comment by RReverser** [comment]
FWIW (for others coming across this issue) these days I use Godbolt instead - it can show Wasm too, has syntax highlight for the output, matches source lines to assembly lines with colors, and the real-time editing is also extremely helpful.

E.g.: https://rust.godbolt.org/z/fTah8jY3x

**Comment by RalfJung** [comment]
Hm, but that doesn't show the function signature, and seeing how the function arguments get compiled to wasm was the entire reason why I wanted to look at the wasm code.

**Comment by RalfJung** [comment]
> What would you like the playground to do in this case?

I would expect playground to pass `--crate-type cdylib` instead of `--crate-type lib` when building a library for "show wasm".

**Comment by RReverser** [comment]
> Hm, but that doesn't show the function signature, and seeing how the function arguments get compiled to wasm was the entire reason why I wanted to look at the wasm code.

It does (still in the non-standard format) if you enable Filter -> Directives. Might be also helpful to disable debug info to reduce number of directives:

![image](https://github.com/rust-lang/rust-playground/assets/557590/c8184a08-e653-4fd3-8a32-7a5e3cee9ba7)

(apologies to @shepmaster for off-topic)
