### ISSUE TITLE
Intermittent bug on Firefox

### ISSUE THREAD

**Issue by panicfarm** [rust-lang/rust-playground#651]
When I click in the code in Firefox, I get an orange rectangular blinking cursor (instead of vertical line cursor in Chrome). And when i type, sometimes instead of characters being entered, this cursor simply moves somewhere, instead of the text being entered.

Firefox 82.0.3 (64-bit Windows 10)

**Comment by shepmaster** [comment]
This rather sounds like the editor keybinding style is set to Vim. Can you check in the config:

![image](https://user-images.githubusercontent.com/174509/99401028-b2452680-28b5-11eb-8372-a0e2c2ad7fc7.png)

If that's not the case, can you try to reproduce that behavior on [the kitchen sink](https://ace.c9.io/build/kitchen-sink.html)? If it fails there, then it's an upstream issue.

**Comment by jackvhall** [comment]
This issue persists, it appears. The problem is that hitting escape (a necessary thing in vim) results in the focus shifting off the textarea.

**Comment by shepmaster** [comment]
No update from OP.
