### ISSUE TITLE
Monaco editor flickers while typing

### ISSUE THREAD

**Issue by tgross35** [rust-lang/rust-playground#885]
This editor flavor has a really bad flickering problem that has appeared recently. I only noticed it the past few days, but @ChaiTRex on the Rust discord said that they saw it a few weeks ago.

Verified on both Windows and MacOS, both Chrome and Firefox.

(gif of the issue)
![chrome_qGIuy57RFX](https://user-images.githubusercontent.com/13724985/213360599-a0c00a7b-580c-41ed-88ff-709f467360d7.gif)

**Comment by shepmaster** [comment]
> observed since the past couple days

That would have made sense as we upgraded dependencies [a few days ago](https://github.com/integer32llc/rust-playground/pull/880)...

> they saw it a few weeks ago

...but this indicates that it's something else.

**Comment by shepmaster** [comment]
Downgrading from react-monaco-editor 0.51.0 to 0.50.1 appears to fix the flicker, so I'm tagging this [as an upstream issue](https://github.com/react-monaco-editor/react-monaco-editor/issues/689).

**Comment by d3x42** [comment]
Same issue. Version downgrade helped

**Comment by shepmaster** [comment]
This has theoretically been fixed upstream and I'm upgrading to that version in #906. That should be merged and deployed in the next few days. Let me know if you see unexpected behavior. I'm going to close this optimistically 🤞 .
