### ISSUE TITLE
Escape key in vim mode moves focus off editor (Firefox)

### ISSUE THREAD

**Issue by halja7** [rust-lang/rust-playground#926]
Hello,

I've noticed when using the Ace Editor in the playground that hitting `<Esc>` (a common thing in vim) causes the focus to shift from the textarea to the browser window. This makes Vim mode essentially unusable, as far as I can tell.

I've confirmed that this does not happen in Chrome. At any rate, there could probably be a listener bound to the UI element rendering the editor that simply captures the event and throws it away or refocuses to the editor.

Thanks

**Comment by shepmaster** [comment]
I cannot reproduce:

![2023-05-03 14 19 09](https://user-images.githubusercontent.com/174509/236008365-3fa5c7d4-849e-4abd-8cc5-3ea5199c514b.gif)

**Comment by mladedav** [comment]
This happens to me in Chrome 116.0.5845.111 on Windows 10.

@shepmaster Is there anything I can provide to help diagnose this?

**Comment by shepmaster** [comment]
On Chrome 116.0.5845.110 (macOS arm64), this continues to work for me:

![2023-08-29 11 46 06](https://github.com/rust-lang/rust-playground/assets/174509/51d63f76-4ad4-4445-83a6-12006bc3b5f8)

> to help diagnose this?

Could you go to the Ace Editor's [kitchen sink](https://ace.c9.io/build/kitchen-sink.html) and see if the same behavior appears there? If so, then it's _probably_ something Ace-specific. If not, then it might be something about how we are using Ace.

You could also try creating a fresh Chrome profile / disabling any extensions and trying again. Do you have any system-global accessories that might grab keyboard input. If it was super easy, I'd even ask if you could create a new Windows user and try from there.

I've got nothing specific.

**Comment by mladedav** [comment]
Kitchen sink works the same way as rust playground for me.

When I tried new anonymous window (without extensions and possibly other configurations?) everything works well both in ace and on the playground. Although the only extension I would guess should matter is vimium which is turned off on the playground.

So at least for me it seems to be an issue with my browser configuration.

Thank you for your time.

**Comment by hariseldon78** [comment]
> Although the only extension I would guess should matter is vimium which is turned off on the playground.

I can confirm that the problem seems indeed caused by the vimium plugin. After adding the exclusion rule in the plugin, saving preferences, and reloading the playground the esc key works correctly!

**Comment by shepmaster** [comment]
I'll assume that's the original case then and close. Thanks all for the debugging!

**Comment by hariseldon78** [comment]
thanks for this awesome tool

**Comment by Blindspot22** [comment]
Wow! this is good. Nice work guys
