### ISSUE TITLE
Broken ace editor theme(s)

### ISSUE THREAD

**Issue by HoloTheDrunk** [rust-lang/rust-playground#941]
The website becomes completely unusable upon selecting a listed but seemingly unavailable ace editor theme.
The theme in this case was `one_dark-css`.

**Expected**: theme changes to one_dark-css.
**Actual**: console displays `Error: couldn't load module ace/theme/one_dark-css or it didn't call define` at `478a968b73ce7d449235.js:2:304601`, website interface completely crashes and just shows the background color.

**Attempted**: clearing the cache, cookies and local storage did not help, but the website works if opened in a private window so though I don't know where the user config is pulled from, it's fairly logically the source of the issue (specifically the `configuration.ace.theme` property).

**Comment by shepmaster** [comment]
Odd. Ace 1.23 changed something with how they package the themes. While I work on that, I'll downgrade to 1.22. 

Thanks for the report!
