### ISSUE TITLE
Support Firefox 91.13.0esr which does not provide crypto.randomUUID

### ISSUE THREAD

**Issue by vam2004** [rust-lang/rust-playground#957]
The playground suddenly stopped loading on **Firefox 91.13.0esr** few months/weeks ago. Looking at the console, it reports that:
```
Uncaught TypeError: e.randomUUID is not a function
    3202 https://play.rust-lang.org/assets/7dfdd7d5deea03736b4c.js:13
    s https://play.rust-lang.org/assets/7dfdd7d5deea03736b4c.js:13
    a https://play.rust-lang.org/assets/7dfdd7d5deea03736b4c.js:13
    O https://play.rust-lang.org/assets/7dfdd7d5deea03736b4c.js:13
    <anonymous> https://play.rust-lang.org/assets/7dfdd7d5deea03736b4c.js:13
    <anonymous> https://play.rust-lang.org/assets/7dfdd7d5deea03736b4c.js:13
```
If a breakpoint is set to all exception, the script will break before the exception is raised and the variable `e` can be examined, which the console reports that it is `Crypto { subtle: SubtleCrypto }`.

The compatibility table in [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID#browser_compatibility) shows that the function `randomUUID` is not available at this version. 

If a breakpoint is put before loading the script (in the first line of this script) and the following script (which generates a hardcoded UUID) is injected, then the page loads successfully:

```js
Crypto.prototype.randomUUID = function(){ return "36b8f84d-df4e-4d49-b662-bcde71a8764f"; }
```

Therefore, a simple polyfill should solve this issue.

**Comment by shepmaster** [comment]
I don’t have much objection to this, but what forces you to stay on that version of Firefox?

**Comment by vam2004** [comment]
I'm only the user of computer, so I don't adiministrative privileges. Maybe I should fill a request to the organization to upgrade the system. But since there is a workaround in the client, then it might not require to be fixed. Anyways, the compatibility break is recent and therefore may affect someone else.

**Comment by shepmaster** [comment]
Do note that Firefox 91 is [no longer supported by Mozilla](https://endoflife.date/firefox). 102 or 115 are the current ESR releases, and what is [officially supported by Rust websites](https://github.com/rust-lang/rust-playground/blob/main/ui/frontend/.browserslistrc).
