### ISSUE TITLE
Running/building does nothing when coming back to a playground tab that was in the background

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-playground#974]
Since 1-2 days, it often happens that I hit Ctrl-Enter to run/build the example, and absolutely nothing happens. The page is then in a broken state, where even if I rpess the button with the moue, nothing happens.

I think I only got into that state when using Ctrl-Enter, but I am not sure. It certainly doesn't always happen, but it happens a lot, and Ctrl-Enter is deep enough in my muscle memory to make this disruptive.

**Comment by RalfJung** [comment]
It just also happened without Ctrl-Enter, so it's not related to using the keyboard vs mouse it seems.

**Comment by shepmaster** [comment]
Yes, I've seen this, but only on other people's computers, never on my own (of course). I didn't see anything *obviously* wrong from the backend's POV when they were triggering the problem, so my instinct is that this will be a frontend-focused problem.

**Comment by shepmaster** [comment]
A small lead I have is that this has to do with the idle timeout, which could explain why I never saw it when I was deliberately trying to reproduce it. The idle timeout is set to 60 seconds, so if you don't build/run within that time frame, that might trigger the problem. As a quick workaround until I have time to sit at the computer later, reloading the page should reconnect you and get a new connection.

**Comment by RalfJung** [comment]
Yes, reloading generally helps. And yes it seems to be more likely to occur when I get back to a playground tab that was in the background for a bit.

**Comment by RalfJung** [comment]
Note that one has to copy the code before reloading; it doesn't always get properly restored when the page got into this broken state.
