### ISSUE TITLE
Failures due to SIGSEGV no longer output noisily

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust-playground#988]
Recent-ish (before October 19th?) changes in how the [Rust Playground](https://play.rust-lang.org) receives/collects/sends data have confounded its ability to collect the stderr of the program and output it, such that when the result is due to e.g. a SIGSEGV, it outputs nothing. This has resulted in [considerable confusion](https://github.com/rust-lang/rust/issues/107975#issuecomment-1771317393), as people are expecting it to segfault noisily.

Does rustc's signal handler need to better-support output redirection in order to restore this, or is it purely incidental?

**Comment by DoubleHyphen** [comment]
```rs
fn main() {
    eprintln!("I'm printing to stderr");
}
```
↑ This appears to work as intended. Thus, `stderr` works at least _some_ of the time.

**Comment by shepmaster** [comment]
We recently changed how the program is run. Previously, the playground server would `Command::spawn` -> `docker` -> `bash` -> `timeout` -> `cargo`. Now it does `Command::spawn` -> `docker` -> `worker` -> `Command::spawn` -> `cargo`.

Notably, the thing that previously printed out the segfault notification (either `bash` or `timeout`, I'm not sure) is no longer in the flow and the playground code gets the exit status directly. Likely I need to use something like [`ExitStatusExt::signal`](https://doc.rust-lang.org/std/os/unix/process/trait.ExitStatusExt.html#tymethod.signal).

**Comment by DoubleHyphen** [comment]
Just tried it on the playground, and yes, the issue appears fixed.
