### ISSUE TITLE
No edition 2024 in the combobox.

### ISSUE THREAD

**Issue by vi** [rust-lang/rust-playground#993]
How do I play with [gen blocks](https://github.com/rust-lang/rust/pull/116447), which seem to require setting edition to unstable so far 2024? Even manually editing `edition=2021` URL parameter does not make it force the new edition.

Maybe 2024 should be added in GUI for Nightly and custom editions (e.g. 2027) be specifiable in the URI?

**Comment by shepmaster** [comment]
> custom editions (e.g. 2027) be specifiable in the URI?

I'm not a fan of unconstrained inputs. We create an edition every three years; I think that having a few days where the playground doesn't have it are an acceptable tradeoff.
